Documentation test
aleksandrgolyk/facebook pull request #56
Opened 2020-10-18 18:18 UTC by aleksandrgolyk

added typography documentation changed typography structure on index.html

2020-10-18 20:51 UTC, okrdima approved these changes

2020-10-18 21:12 UTC, GingerBoy14 requested changes

2020-10-18 21:12 UTC, GingerBoy14 commented on src/styles/helpers/typography/advanced-text-classes.scss
> +
why you added !important flag to color style?

2020-10-18 21:12 UTC, GingerBoy14 commented on src/documentation/typography/typography.html
> +    </div>
different spacing

2020-10-18 21:12 UTC, GingerBoy14 commented on src/documentation/typography/typography.html
> +          </span>
different spacing

2020-10-19 06:19 UTC, aleksandrgolyk commented on src/styles/helpers/typography/advanced-text-classes.scss
> +
because the team decide to add more  style weight by using !important and without it presets classes cant implement their own color

2020-10-19 06:22 UTC, aleksandrgolyk commented on src/documentation/typography/typography.html
> +    </div>
fixed

2020-10-19 06:22 UTC, aleksandrgolyk commented on src/documentation/typography/typography.html
> +          </span>
fixed

2020-10-19 06:51 UTC, GingerBoy14 approved these changes

2020-10-19 06:51 UTC, merged