Added icons config
aleksandrgolyk/facebook pull request #6
Opened 2020-10-07 15:28 UTC by AlexFry123

Added icons config, please review

2020-10-07 15:40 UTC, sashka2131 approved these changes

2020-10-07 15:42 UTC, aleksandrgolyk requested changes
Remove strict colors. Use variables!!!

2020-10-07 15:45 UTC, 5P4C3GR33D requested changes
Inherit color variables, don't use hardcode.

2020-10-07 19:42 UTC, sashka2131 submitted a review, later dismissed

2020-10-08 08:21 UTC, 5P4C3GR33D approved these changes

2020-10-08 08:32 UTC, aleksandrgolyk approved these changes

2020-10-08 08:32 UTC, merged